POST http://localhost:8080/api/fetcher
Content-Type: application/json

{
  "url": "https://httpbin.org/range/10",
  "interval":30
}

###
GET http://localhost:8080/api/fetcher
Content-Type: application/json

{
}
###
GET http://localhost:8080/api/fetcher/22/history
Content-Type: application/json

{
}
###
DELETE http://localhost:8080/api/fetcher/22
Content-Type: application/json

{
}

###
PATCH http://localhost:8080/api/fetcher/22
Content-Type: application/json

{
  "interval":2
}
