POST http://localhost:8080/api/fetcher
Content-Type: application/json

{
  "url": "https://httpbin.org/range/10",
  "interval":8
}

###
POST http://localhost:8080/api/fetcher
Content-Type: application/json

{
  "url": "https://httpbin.org/range/10",
  "interval":2
}
###
GET http://localhost:8080/api/fetcher/1/history
Content-Type: application/json

{
}
###
GET http://localhost:8080/api/fetcher
Content-Type: application/json

{
}

###
DELETE http://localhost:8080/api/fetcher/28
Content-Type: application/json

{
}

###
PATCH http://localhost:8080/api/fetcher/31
Content-Type: application/json

{
  "interval":6
}
